/***************************************************************/
/*                                                             */
/*      PROJECT NAME :  renesas_control_7_22                   */
/*      FILE         :  stacksct.h                             */
/*      DESCRIPTION  :  Setting of Stack area                  */
/*      CPU SERIES   :  RX200                                  */
/*      CPU TYPE     :  RX23T                                  */
/*                                                             */
/*      This file is generated by e2 studio.                   */
/*                                                             */
/***************************************************************/
#pragma stacksize su=0x100
#pragma stacksize si=0x300